"""change webhook event_types from ARRAY to JSON for SQLite compatibility

Revision ID: 5b3bb8ea7a3f
Revises: 95ab60098bd3
Create Date: 2026-01-24 11:01:24.402037

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5b3bb8ea7a3f"
down_revision = "95ab60098bd3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_configurations",
        "event_types",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_configurations",
        "event_types",
        existing_type=sa.JSON(),
        type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
