"""initial_schema_with_webhooks_and_advanced_orders

Revision ID: 95ab60098bd3
Revises:
Create Date: 2026-01-24 01:53:41.780111

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "95ab60098bd3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ostium_wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider_type",
            sa.String(length=50),
            nullable=False,
            comment="Wallet provider type (privy/dynamic)",
        ),
        sa.Column(
            "provider_wallet_id",
            sa.String(length=255),
            nullable=False,
            comment="Provider-specific wallet ID",
        ),
        sa.Column(
            "wallet_address",
            sa.String(length=42),
            nullable=False,
            comment="Ethereum wallet address",
        ),
        sa.Column(
            "network", sa.String(length=20), nullable=False, comment="Network (testnet/mainnet)"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Active status"),
        sa.Column(
            "wallet_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Provider-specific metadata",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ostium_wallets_id"), "ostium_wallets", ["id"], unique=False)
    op.create_index(op.f("ix_ostium_wallets_network"), "ostium_wallets", ["network"], unique=False)
    op.create_index(
        op.f("ix_ostium_wallets_provider_type"), "ostium_wallets", ["provider_type"], unique=False
    )
    op.create_index(
        op.f("ix_ostium_wallets_provider_wallet_id"),
        "ostium_wallets",
        ["provider_wallet_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ostium_wallets_wallet_address"), "ostium_wallets", ["wallet_address"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("auth0_user_id", sa.String(length=255), nullable=True),
        sa.Column("privy_user_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "auth_method",
            sa.Enum("EMAIL", "GOOGLE", "APPLE", "WALLET", name="authmethod"),
            nullable=False,
        ),
        sa.Column(
            "wallet_type", sa.Enum("MPC", "EXTERNAL", "NONE", name="wallettype"), nullable=True
        ),
        sa.Column("wallet_address", sa.String(length=42), nullable=True),
        sa.Column("mpc_wallet_id", sa.Integer(), nullable=True),
        sa.Column(
            "feature_access_level",
            sa.Enum("FULL", "LIMITED", name="featureaccesslevel"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mpc_wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_auth0_user_id"), "users", ["auth0_user_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_privy_user_id"), "users", ["privy_user_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(op.f("ix_users_wallet_address"), "users", ["wallet_address"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("provider_wallet_id", sa.String(length=255), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("network", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("wallet_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_id"), "wallets", ["id"], unique=False)
    op.create_index(
        "ix_wallets_provider_wallet_id",
        "wallets",
        ["provider_type", "provider_wallet_id"],
        unique=False,
    )
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    op.create_index("ix_wallets_user_primary", "wallets", ["user_id", "is_primary"], unique=False)
    op.create_index(op.f("ix_wallets_wallet_address"), "wallets", ["wallet_address"], unique=False)
    op.create_table(
        "app_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=True),
        sa.Column("config_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_app_config_category", "app_configurations", ["category"], unique=False)
    op.create_index(
        "idx_app_config_key_active", "app_configurations", ["config_key", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_app_configurations_category"), "app_configurations", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_app_configurations_config_key"), "app_configurations", ["config_key"], unique=True
    )
    op.create_index(
        op.f("ix_app_configurations_created_by"), "app_configurations", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_app_configurations_id"), "app_configurations", ["id"], unique=False)
    op.create_index(
        op.f("ix_app_configurations_is_active"), "app_configurations", ["is_active"], unique=False
    )
    op.create_table(
        "deposits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_address", sa.String(length=42), nullable=False),
        sa.Column("token_symbol", sa.String(length=20), nullable=False),
        sa.Column("chain", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("transaction_hash", sa.String(length=66), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deposits_id"), "deposits", ["id"], unique=False)
    op.create_index("ix_deposits_provider", "deposits", ["provider"], unique=False)
    op.create_index(op.f("ix_deposits_status"), "deposits", ["status"], unique=False)
    op.create_index("ix_deposits_transaction_hash", "deposits", ["transaction_hash"], unique=False)
    op.create_index(op.f("ix_deposits_user_id"), "deposits", ["user_id"], unique=False)
    op.create_index("ix_deposits_user_status", "deposits", ["user_id", "status"], unique=False)
    op.create_table(
        "oauth_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_connections_id"), "oauth_connections", ["id"], unique=False)
    op.create_index(
        "ix_oauth_connections_provider_user_id",
        "oauth_connections",
        ["provider", "provider_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_connections_user_id"), "oauth_connections", ["user_id"], unique=False
    )
    op.create_index(
        "ix_oauth_connections_user_provider",
        "oauth_connections",
        ["user_id", "provider"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("quote", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_order_id", sa.String(length=255), nullable=True),
        sa.Column("transaction_hash", sa.String(length=66), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("trailing_offset", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("linked_order_id", sa.Integer(), nullable=True),
        sa.Column("is_trailing_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("filled_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["linked_order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(
        "ix_orders_provider_order_id", "orders", ["provider", "provider_order_id"], unique=False
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_index("ix_orders_user_status", "orders", ["user_id", "status"], unique=False)
    op.create_table(
        "ostium_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("private_key_encrypted", sa.String(length=500), nullable=False),
        sa.Column("rpc_url", sa.String(length=500), nullable=False),
        sa.Column("network", sa.String(length=20), nullable=False),
        sa.Column("verbose", sa.Boolean(), nullable=False),
        sa.Column("slippage_percentage", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("default_fee_percentage", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("min_fee", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("max_fee", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("timeout", sa.Integer(), nullable=False),
        sa.Column("retry_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_delay", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ostium_settings_active", "ostium_settings", ["is_active", "created_at"], unique=False
    )
    op.create_index("idx_ostium_settings_version", "ostium_settings", ["version"], unique=False)
    op.create_index(
        op.f("ix_ostium_settings_created_at"), "ostium_settings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ostium_settings_created_by"), "ostium_settings", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_ostium_settings_id"), "ostium_settings", ["id"], unique=False)
    op.create_index(
        op.f("ix_ostium_settings_is_active"), "ostium_settings", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_ostium_settings_version"), "ostium_settings", ["version"], unique=False
    )
    op.create_table(
        "provider_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=50), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("config_data", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_provider_config_active",
        "provider_configurations",
        ["provider_name", "provider_type", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_provider_config_version",
        "provider_configurations",
        ["provider_name", "provider_type", "version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_configurations_created_by"),
        "provider_configurations",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_configurations_id"), "provider_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_provider_configurations_is_active"),
        "provider_configurations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_configurations_provider_name"),
        "provider_configurations",
        ["provider_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_configurations_provider_type"),
        "provider_configurations",
        ["provider_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_configurations_version"),
        "provider_configurations",
        ["version"],
        unique=False,
    )
    op.create_table(
        "risk_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("asset", sa.String(length=20), nullable=True),
        sa.Column("max_leverage", sa.Integer(), nullable=False),
        sa.Column("max_position_size", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("min_margin", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_limits_asset"), "risk_limits", ["asset"], unique=False)
    op.create_index(op.f("ix_risk_limits_id"), "risk_limits", ["id"], unique=False)
    op.create_index("ix_risk_limits_user_asset", "risk_limits", ["user_id", "asset"], unique=False)
    op.create_index(op.f("ix_risk_limits_user_id"), "risk_limits", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("device_info", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_sessions_refresh_token_hash"), "sessions", ["refresh_token_hash"], unique=False
    )
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=False)
    op.create_index("ix_sessions_user_expires", "sessions", ["user_id", "expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("total_pnl", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("total_volume", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("average_leverage", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("best_trade_pnl", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("worst_trade_pnl", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("last_trade_at", sa.DateTime(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_stats_id"), "user_stats", ["id"], unique=False)
    op.create_index(op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=True)
    op.create_table(
        "wallet_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("wallet_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("provider_wallet_id", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallet_connections_id"), "wallet_connections", ["id"], unique=False)
    op.create_index(
        op.f("ix_wallet_connections_user_id"), "wallet_connections", ["user_id"], unique=False
    )
    op.create_index(
        "ix_wallet_connections_user_primary",
        "wallet_connections",
        ["user_id", "is_primary"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_connections_wallet_address"),
        "wallet_connections",
        ["wallet_address"],
        unique=False,
    )
    op.create_table(
        "webhook_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.Column("event_types", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_webhook_configs_user_active",
        "webhook_configurations",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_configurations_id"), "webhook_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_configurations_user_id"),
        "webhook_configurations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "token_swaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deposit_id", sa.Integer(), nullable=False),
        sa.Column("from_token", sa.String(length=42), nullable=False),
        sa.Column("to_token", sa.String(length=42), nullable=False),
        sa.Column("from_chain", sa.String(length=50), nullable=False),
        sa.Column("to_chain", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("swap_provider", sa.String(length=50), nullable=False),
        sa.Column("swap_status", sa.String(length=20), nullable=False),
        sa.Column("swap_transaction_hash", sa.String(length=66), nullable=True),
        sa.Column("estimated_output", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("actual_output", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["deposit_id"], ["deposits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_token_swaps_deposit", "token_swaps", ["deposit_id"], unique=False)
    op.create_index(op.f("ix_token_swaps_deposit_id"), "token_swaps", ["deposit_id"], unique=False)
    op.create_index(op.f("ix_token_swaps_id"), "token_swaps", ["id"], unique=False)
    op.create_index("ix_token_swaps_status", "token_swaps", ["swap_status"], unique=False)
    op.create_index(
        op.f("ix_token_swaps_swap_status"), "token_swaps", ["swap_status"], unique=False
    )
    op.create_index(
        "ix_token_swaps_transaction_hash", "token_swaps", ["swap_transaction_hash"], unique=False
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("pair_id", sa.Integer(), nullable=False),
        sa.Column("trade_index", sa.Integer(), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("quote", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("collateral", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tp_price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("sl_price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("pnl", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("pnl_percentage", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_trade_id", sa.String(length=255), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    op.create_index(op.f("ix_trades_order_id"), "trades", ["order_id"], unique=False)
    op.create_index(
        "ix_trades_pair_trade_index", "trades", ["pair_id", "trade_index"], unique=False
    )
    op.create_index(
        "ix_trades_provider_trade_id", "trades", ["provider", "provider_trade_id"], unique=False
    )
    op.create_index(op.f("ix_trades_status"), "trades", ["status"], unique=False)
    op.create_index(op.f("ix_trades_user_id"), "trades", ["user_id"], unique=False)
    op.create_index("ix_trades_user_status", "trades", ["user_id", "status"], unique=False)
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("delivery_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhook_configurations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_delivery_id"),
        "webhook_deliveries",
        ["delivery_id"],
        unique=True,
    )
    op.create_index(op.f("ix_webhook_deliveries_id"), "webhook_deliveries", ["id"], unique=False)
    op.create_index(
        "ix_webhook_deliveries_retry",
        "webhook_deliveries",
        ["success", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_deliveries_webhook_event",
        "webhook_deliveries",
        ["webhook_id", "event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("quote", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("size", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("collateral", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("unrealized_pnl_percentage", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("liquidation_price", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("margin_ratio", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_index(op.f("ix_positions_trade_id"), "positions", ["trade_id"], unique=True)
    op.create_index("ix_positions_user", "positions", ["user_id"], unique=False)
    op.create_index(op.f("ix_positions_user_id"), "positions", ["user_id"], unique=False)
    op.create_table(
        "trade_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_history_id"), "trade_history", ["id"], unique=False)
    op.create_index(op.f("ix_trade_history_trade_id"), "trade_history", ["trade_id"], unique=False)
    op.create_index(op.f("ix_trade_history_user_id"), "trade_history", ["user_id"], unique=False)
    op.create_table(
        "risk_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("current_value", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_events_event_type"), "risk_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_risk_events_id"), "risk_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_risk_events_position_id"), "risk_events", ["position_id"], unique=False
    )
    op.create_index(
        "ix_risk_events_user_created", "risk_events", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_risk_events_user_id"), "risk_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_events_user_id"), table_name="risk_events")
    op.drop_index("ix_risk_events_user_created", table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_position_id"), table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_id"), table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_event_type"), table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index(op.f("ix_trade_history_user_id"), table_name="trade_history")
    op.drop_index(op.f("ix_trade_history_trade_id"), table_name="trade_history")
    op.drop_index(op.f("ix_trade_history_id"), table_name="trade_history")
    op.drop_table("trade_history")
    op.drop_index(op.f("ix_positions_user_id"), table_name="positions")
    op.drop_index("ix_positions_user", table_name="positions")
    op.drop_index(op.f("ix_positions_trade_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.drop_index("ix_webhook_deliveries_webhook_event", table_name="webhook_deliveries")
    op.drop_index("ix_webhook_deliveries_retry", table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_delivery_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("ix_trades_user_status", table_name="trades")
    op.drop_index(op.f("ix_trades_user_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_status"), table_name="trades")
    op.drop_index("ix_trades_provider_trade_id", table_name="trades")
    op.drop_index("ix_trades_pair_trade_index", table_name="trades")
    op.drop_index(op.f("ix_trades_order_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_token_swaps_transaction_hash", table_name="token_swaps")
    op.drop_index(op.f("ix_token_swaps_swap_status"), table_name="token_swaps")
    op.drop_index("ix_token_swaps_status", table_name="token_swaps")
    op.drop_index(op.f("ix_token_swaps_id"), table_name="token_swaps")
    op.drop_index(op.f("ix_token_swaps_deposit_id"), table_name="token_swaps")
    op.drop_index("ix_token_swaps_deposit", table_name="token_swaps")
    op.drop_table("token_swaps")
    op.drop_index(op.f("ix_webhook_configurations_user_id"), table_name="webhook_configurations")
    op.drop_index(op.f("ix_webhook_configurations_id"), table_name="webhook_configurations")
    op.drop_index("ix_webhook_configs_user_active", table_name="webhook_configurations")
    op.drop_table("webhook_configurations")
    op.drop_index(op.f("ix_wallet_connections_wallet_address"), table_name="wallet_connections")
    op.drop_index("ix_wallet_connections_user_primary", table_name="wallet_connections")
    op.drop_index(op.f("ix_wallet_connections_user_id"), table_name="wallet_connections")
    op.drop_index(op.f("ix_wallet_connections_id"), table_name="wallet_connections")
    op.drop_table("wallet_connections")
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.drop_index(op.f("ix_user_stats_id"), table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index("ix_sessions_user_expires", table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_risk_limits_user_id"), table_name="risk_limits")
    op.drop_index("ix_risk_limits_user_asset", table_name="risk_limits")
    op.drop_index(op.f("ix_risk_limits_id"), table_name="risk_limits")
    op.drop_index(op.f("ix_risk_limits_asset"), table_name="risk_limits")
    op.drop_table("risk_limits")
    op.drop_index(op.f("ix_provider_configurations_version"), table_name="provider_configurations")
    op.drop_index(
        op.f("ix_provider_configurations_provider_type"), table_name="provider_configurations"
    )
    op.drop_index(
        op.f("ix_provider_configurations_provider_name"), table_name="provider_configurations"
    )
    op.drop_index(
        op.f("ix_provider_configurations_is_active"), table_name="provider_configurations"
    )
    op.drop_index(op.f("ix_provider_configurations_id"), table_name="provider_configurations")
    op.drop_index(
        op.f("ix_provider_configurations_created_by"), table_name="provider_configurations"
    )
    op.drop_index("idx_provider_config_version", table_name="provider_configurations")
    op.drop_index("idx_provider_config_active", table_name="provider_configurations")
    op.drop_table("provider_configurations")
    op.drop_index(op.f("ix_ostium_settings_version"), table_name="ostium_settings")
    op.drop_index(op.f("ix_ostium_settings_is_active"), table_name="ostium_settings")
    op.drop_index(op.f("ix_ostium_settings_id"), table_name="ostium_settings")
    op.drop_index(op.f("ix_ostium_settings_created_by"), table_name="ostium_settings")
    op.drop_index(op.f("ix_ostium_settings_created_at"), table_name="ostium_settings")
    op.drop_index("idx_ostium_settings_version", table_name="ostium_settings")
    op.drop_index("idx_ostium_settings_active", table_name="ostium_settings")
    op.drop_table("ostium_settings")
    op.drop_index("ix_orders_user_status", table_name="orders")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index("ix_orders_provider_order_id", table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_oauth_connections_user_provider", table_name="oauth_connections")
    op.drop_index(op.f("ix_oauth_connections_user_id"), table_name="oauth_connections")
    op.drop_index("ix_oauth_connections_provider_user_id", table_name="oauth_connections")
    op.drop_index(op.f("ix_oauth_connections_id"), table_name="oauth_connections")
    op.drop_table("oauth_connections")
    op.drop_index("ix_deposits_user_status", table_name="deposits")
    op.drop_index(op.f("ix_deposits_user_id"), table_name="deposits")
    op.drop_index("ix_deposits_transaction_hash", table_name="deposits")
    op.drop_index(op.f("ix_deposits_status"), table_name="deposits")
    op.drop_index("ix_deposits_provider", table_name="deposits")
    op.drop_index(op.f("ix_deposits_id"), table_name="deposits")
    op.drop_table("deposits")
    op.drop_index(op.f("ix_app_configurations_is_active"), table_name="app_configurations")
    op.drop_index(op.f("ix_app_configurations_id"), table_name="app_configurations")
    op.drop_index(op.f("ix_app_configurations_created_by"), table_name="app_configurations")
    op.drop_index(op.f("ix_app_configurations_config_key"), table_name="app_configurations")
    op.drop_index(op.f("ix_app_configurations_category"), table_name="app_configurations")
    op.drop_index("idx_app_config_key_active", table_name="app_configurations")
    op.drop_index("idx_app_config_category", table_name="app_configurations")
    op.drop_table("app_configurations")
    op.drop_index(op.f("ix_wallets_wallet_address"), table_name="wallets")
    op.drop_index("ix_wallets_user_primary", table_name="wallets")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index("ix_wallets_provider_wallet_id", table_name="wallets")
    op.drop_index(op.f("ix_wallets_id"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_users_wallet_address"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_privy_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_auth0_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ostium_wallets_wallet_address"), table_name="ostium_wallets")
    op.drop_index(op.f("ix_ostium_wallets_provider_wallet_id"), table_name="ostium_wallets")
    op.drop_index(op.f("ix_ostium_wallets_provider_type"), table_name="ostium_wallets")
    op.drop_index(op.f("ix_ostium_wallets_network"), table_name="ostium_wallets")
    op.drop_index(op.f("ix_ostium_wallets_id"), table_name="ostium_wallets")
    op.drop_table("ostium_wallets")
    # ### end Alembic commands ###
